---
- include_role:
    name: microk8s

- include_role:
    name: dt-activegate-classic

- include_role:
    name: dt-oneagent-classic

- include_role:
    name: monaco

- include_role:
    name: monaco
    tasks_from: dt-cleanup

- include_role:
    name: keptn
  when: cloud_automation_flavor is defined and cloud_automation_flavor == "KEPTN"

- include_role:
    name: cloudautomation
  when: cloud_automation_flavor is defined and cloud_automation_flavor == "CLOUD_AUTOMATION"

- include_role:
    name: gitea

- include_role:
    name: gitea
    tasks_from: source-secret
  when: gitea_access_token is not defined or gitea_username is not defined or gitea_password is not defined

- include_role:
    name: gitea
    tasks_from: create-organization
  vars:
    gitea_org: "{{ demo_appsec_org }}"

- include_role:
    name: gitea
    tasks_from: create-repository
  vars:
    gitea_org: "{{ demo_appsec_org }}"
    gitea_repo: "{{ demo_appsec_repo_name }}"

- include_role:
    name: gitea
    tasks_from: create-organization
  vars:
    gitea_org: "{{ hot_appsec_org }}"

- include_role:
    name: gitea
    tasks_from: create-repository
  vars:
    gitea_org: "{{ hot_appsec_org }}"
    gitea_repo: "{{ hot_appsec_repo_name }}"

- include_role:
    name: repository
  vars:
    repo_src: "{{ item.repo_src }}"
    git_org: "{{ item.git_org }}"
    git_repo: "{{ item.repo_target }}"
    git_username: "{{ gitea_username }}"
    git_password: "{{ gitea_password }}"
    git_domain: "{{ gitea_domain }}"
    git_remote: "gitea"
  loop:
  - { repo_target: "{{ hot_appsec_repo_name }}", repo_src: "{{ role_path }}/files/repos/hot-appsec", git_org: "{{ hot_appsec_org }}" }
  when: new_repo_created is defined and new_repo_created == true

- include_role:
    name: app-simplenode
  vars:
    git_username: "{{ gitea_username }}"
    git_password: "{{ gitea_password }}"
    git_domain: "{{ gitea_domain }}"
    git_remote: "gitea"
    git_org_name: "{{ demo_appsec_org }}"
    repo_name: "{{ demo_appsec_repo_name }}"
  when: new_repo_created is defined and new_repo_created == true

- set_fact:
    include_jenkins_value_file: "{{ role_path }}/templates/hot-appsec-jobs.yml.j2"


- include_role:
    name: jenkins
    tasks_from: template-values-file
  vars:
    git_repo_demo: "{{ demo_appsec_repo_name }}"
    git_org_demo: "{{ demo_appsec_org }}"
    git_domain: "gitea.{{ ingress_domain }}"



- include_role:
    name: jenkins


- file:
    path: "/home/{{ ace_box_user }}/ansible/roles/dashboard/files/helm-values"
    state: directory
    
- include_role:
    name: dashboard


